spring.application.name=ReactData
#server.port=10000
server.port=${PORT:8080}
razorpay.key.id=rzp_test_RQZn01yVLde3J8
razorpay.key.secret=EN0AMuJuYhZjbLXFUW9kMuof

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

#spring.datasource.driver-class-name=org.postgresql.Driver
#spring.datasource.url=jdbc:postgresql://localhost:5432/reactdb_pg
#spring.datasource.username=postgres
#spring.datasource.password=srinadh

spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

spring.datasource.driver-class-name=org.postgresql.Driver
spring.datasource.url=jdbc:postgresql://dpg-d4i5tdmmcj7s73cdmbjg-a.oregon-postgres.render.com:5432/reactdb_render?sslmode=require
spring.datasource.username=reactdb_render_user
spring.datasource.password=FuqbdBZURL7MrJD6ulm18ZWBZP5HR7vD

