spring.application.name=ReactData
server.port=10000
razorpay.key.id=rzp_test_RQZn01yVLde3J8
razorpay.key.secret=EN0AMuJuYhZjbLXFUW9kMuof

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.datasource.url=jdbc:mysql://localhost:3306/reactdb
spring.datasource.username=root
spring.datasource.password=Chinna@66

